DROP TABLE
IF EXISTS pubud.sys_menu;

CREATE TABLE pubud.sys_menu (
	`MENU_ID` BIGINT NOT NULL auto_increment PRIMARY KEY,
	`MENU_CODE` VARCHAR(30) NOT NULL,
	`MENU_ICON` VARCHAR(30) NOT NULL,
	`MENU_NAME` VARCHAR(255) NOT NULL,
	`DESCRIPTION` VARCHAR(255),
	`RESOURCE_ID` BIGINT,
	`PARENT_ID` BIGINT,
	`MENU_ORDER` BIGINT,
	OBJECT_VERSION_NUMBER BIGINT DEFAULT 1 NOT NULL,
	CREATION_DATE datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATED_BY BIGINT NOT NULL DEFAULT - 1,
	LAST_UPDATED_BY BIGINT NOT NULL DEFAULT - 1,
	LAST_UPDATE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE pubud.sys_menu COMMENT '菜单表';

ALTER TABLE pubud.sys_menu MODIFY `MENU_ID` BIGINT NOT NULL auto_increment COMMENT '表ID，主键，供其他表做外键';

ALTER TABLE pubud.sys_menu MODIFY `MENU_CODE` VARCHAR(30) NOT NULL COMMENT '菜单编码';

ALTER TABLE pubud.sys_menu MODIFY `MENU_ICON` VARCHAR(30) NOT NULL COMMENT '菜单图标';

ALTER TABLE pubud.sys_menu MODIFY `MENU_NAME` VARCHAR(255) NOT NULL COMMENT '菜单名称（标题）';

ALTER TABLE pubud.sys_menu MODIFY `DESCRIPTION` VARCHAR(255) COMMENT '说明';

ALTER TABLE pubud.sys_menu MODIFY `RESOURCE_ID` BIGINT COMMENT '资源ID';

ALTER TABLE pubud.sys_menu MODIFY `PARENT_ID` BIGINT COMMENT '父菜单ID';

ALTER TABLE pubud.sys_menu MODIFY `MENU_ORDER` BIGINT COMMENT '排序';

ALTER TABLE pubud.sys_menu MODIFY `OBJECT_VERSION_NUMBER` BIGINT DEFAULT 1 NOT NULL COMMENT '行版本号，用来处理锁';

ALTER TABLE pubud.sys_menu MODIFY `CREATION_DATE` datetime DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间';

ALTER TABLE pubud.sys_menu MODIFY `CREATED_BY` BIGINT DEFAULT 1 NOT NULL COMMENT '创建人';

ALTER TABLE pubud.sys_menu MODIFY `LAST_UPDATED_BY` BIGINT DEFAULT 1 NOT NULL COMMENT '上次更新人';

ALTER TABLE pubud.sys_menu MODIFY `LAST_UPDATE_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '上次更新时间';