DROP TABLE
IF EXISTS pubud.sys_resource;

CREATE TABLE pubud.sys_resource (
	`RESOURCE_ID` BIGINT NOT NULL auto_increment PRIMARY KEY,
	`RESOURCE_TYPE` VARCHAR(30) NOT NULL,
	`RESOURCE_CODE` VARCHAR(255) NOT NULL,
	`RESOURCE_URL` VARCHAR(255) NOT NULL,
	`RESOURCE_NAME` VARCHAR(255) NOT NULL,
	OBJECT_VERSION_NUMBER BIGINT DEFAULT 1 NOT NULL,
	CREATION_DATE datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATED_BY BIGINT NOT NULL DEFAULT - 1,
	LAST_UPDATED_BY BIGINT NOT NULL DEFAULT - 1,
	LAST_UPDATE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE pubud.sys_resource COMMENT '资源表';

ALTER TABLE pubud.sys_resource MODIFY `RESOURCE_ID` BIGINT NOT NULL auto_increment COMMENT '表ID，主键，供其他表做外键';

ALTER TABLE pubud.sys_resource MODIFY `RESOURCE_TYPE` VARCHAR(30) NOT NULL COMMENT '资源类型';

ALTER TABLE pubud.sys_resource MODIFY `RESOURCE_CODE` VARCHAR(255) NOT NULL COMMENT '资源编码';

ALTER TABLE pubud.sys_resource MODIFY `RESOURCE_URL` VARCHAR(255) NOT NULL COMMENT '资源地址';

ALTER TABLE pubud.sys_resource MODIFY `RESOURCE_NAME` VARCHAR(255) NOT NULL COMMENT '资源名称';

ALTER TABLE pubud.sys_resource MODIFY `OBJECT_VERSION_NUMBER` BIGINT DEFAULT 1 NOT NULL COMMENT '行版本号，用来处理锁';

ALTER TABLE pubud.sys_resource MODIFY `CREATION_DATE` datetime DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间';

ALTER TABLE pubud.sys_resource MODIFY `CREATED_BY` BIGINT DEFAULT 1 NOT NULL COMMENT '创建人';

ALTER TABLE pubud.sys_resource MODIFY `LAST_UPDATED_BY` BIGINT DEFAULT 1 NOT NULL COMMENT '上次更新人';

ALTER TABLE pubud.sys_resource MODIFY `LAST_UPDATE_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '上次更新时间';