DROP TABLE
IF EXISTS pubud.sys_menu_t;

CREATE TABLE pubud.sys_menu_t (
	`ID` BIGINT NOT NULL auto_increment PRIMARY KEY,
	`CODE` VARCHAR(32) NOT NULL,
	`NAME` VARCHAR(32) NOT NULL,
	`ICON` VARCHAR(32) NOT NULL,
	`PATH` VARCHAR(64) NOT NULL,
	`COMPONENT` VARCHAR(64) NOT NULL,
	`TITLE` VARCHAR(255),
	`PARENT_ID` BIGINT,
	`ORDER` BIGINT,
	OBJECT_VERSION_NUMBER BIGINT DEFAULT 1 NOT NULL,
	CREATION_DATE datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATED_BY BIGINT NOT NULL DEFAULT - 1,
	LAST_UPDATED_BY BIGINT NOT NULL DEFAULT - 1,
	LAST_UPDATE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE pubud.sys_menu_t COMMENT '菜单表';

ALTER TABLE pubud.sys_menu_t MODIFY `ID` BIGINT NOT NULL auto_increment COMMENT '表ID，主键，供其他表做外键';

ALTER TABLE pubud.sys_menu_t MODIFY `CODE` VARCHAR(32) NOT NULL COMMENT '菜单编码';

ALTER TABLE pubud.sys_menu_t MODIFY `NAME` VARCHAR(32) NOT NULL COMMENT '菜单名称';

ALTER TABLE pubud.sys_menu_t MODIFY `ICON` VARCHAR(32) NOT NULL COMMENT '菜单图标';

ALTER TABLE pubud.sys_menu_t MODIFY `PATH` VARCHAR(64) NOT NULL COMMENT '菜单路径';

ALTER TABLE pubud.sys_menu_t MODIFY `COMPONENT` VARCHAR(64) NOT NULL COMMENT '视图地址';

ALTER TABLE pubud.sys_menu_t MODIFY `TITLE` VARCHAR(255) COMMENT '菜单标题';

ALTER TABLE pubud.sys_menu_t MODIFY `PARENT_ID` BIGINT COMMENT '父菜单ID';

ALTER TABLE pubud.sys_menu_t MODIFY `ORDER` BIGINT COMMENT '排序';

ALTER TABLE pubud.sys_menu_t MODIFY `OBJECT_VERSION_NUMBER` BIGINT DEFAULT 1 NOT NULL COMMENT '行版本号，用来处理锁';

ALTER TABLE pubud.sys_menu_t MODIFY `CREATION_DATE` datetime DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间';

ALTER TABLE pubud.sys_menu_t MODIFY `CREATED_BY` BIGINT DEFAULT 1 NOT NULL COMMENT '创建人';

ALTER TABLE pubud.sys_menu_t MODIFY `LAST_UPDATED_BY` BIGINT DEFAULT 1 NOT NULL COMMENT '上次更新人';

ALTER TABLE pubud.sys_menu_t MODIFY `LAST_UPDATE_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '上次更新时间';