DROP TABLE
IF EXISTS pubud.sys_user;

CREATE TABLE pubud.sys_user (
	`USER_ID` BIGINT NOT NULL auto_increment PRIMARY KEY,
	`USERNAME` VARCHAR (255) NOT NULL,
	`DISPLAY_NAME` VARCHAR (255) NOT NULL,
	`PASSWORD` VARCHAR (255),
	`EMAIL` VARCHAR (255) DEFAULT NULL,
	`PHONE` VARCHAR (255) NOT NULL,
	`EMPLOYEE_ID` BIGINT,
	OBJECT_VERSION_NUMBER BIGINT DEFAULT 1 NOT NULL,
	CREATION_DATE datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATED_BY BIGINT NOT NULL DEFAULT - 1,
	LAST_UPDATED_BY BIGINT NOT NULL DEFAULT - 1,
	LAST_UPDATE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE pubud.sys_user COMMENT '用户信息表';

ALTER TABLE pubud.sys_user MODIFY `USER_ID` BIGINT NOT NULL auto_increment COMMENT '表ID，主键，供其他表做外键';

ALTER TABLE pubud.sys_user MODIFY `USERNAME` VARCHAR (255) NOT NULL COMMENT '用户名';

ALTER TABLE pubud.sys_user MODIFY `DISPLAY_NAME` VARCHAR (255) NOT NULL COMMENT '显示名称';

ALTER TABLE pubud.sys_user MODIFY `PASSWORD` VARCHAR (255) NOT NULL COMMENT '密码（加密）';

ALTER TABLE pubud.sys_user MODIFY `EMAIL` VARCHAR (255) COMMENT '邮箱';

ALTER TABLE pubud.sys_user MODIFY `PHONE` VARCHAR (255) NOT NULL COMMENT '电话';

ALTER TABLE pubud.sys_user MODIFY `EMPLOYEE_ID` BIGINT COMMENT '员工id';

ALTER TABLE pubud.sys_user MODIFY `OBJECT_VERSION_NUMBER` BIGINT DEFAULT 1 NOT NULL COMMENT '行版本号，用来处理锁';

ALTER TABLE pubud.sys_user MODIFY `CREATION_DATE` datetime DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间';

ALTER TABLE pubud.sys_user MODIFY `CREATED_BY` BIGINT DEFAULT 1 NOT NULL COMMENT '创建人';

ALTER TABLE pubud.sys_user MODIFY `LAST_UPDATED_BY` BIGINT DEFAULT 1 NOT NULL COMMENT '上次更新人';

ALTER TABLE pubud.sys_user MODIFY `LAST_UPDATE_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '上次更新时间';