DROP TABLE
IF EXISTS pubud.sys_role_resource;

CREATE TABLE pubud.sys_role_resource (
	`ROLE_RESOURCE_ID` BIGINT NOT NULL auto_increment PRIMARY KEY,
	`ROLE_ID` BIGINT NOT NULL,
	`RESOURCE_ID` BIGINT NOT NULL,
	OBJECT_VERSION_NUMBER BIGINT DEFAULT 1 NOT NULL,
	CREATION_DATE datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATED_BY BIGINT NOT NULL DEFAULT - 1,
	LAST_UPDATED_BY BIGINT NOT NULL DEFAULT - 1,
	LAST_UPDATE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE pubud.sys_role_resource COMMENT '角色资源关系表';

ALTER TABLE pubud.sys_role_resource MODIFY `ROLE_RESOURCE_ID` BIGINT NOT NULL auto_increment COMMENT '表ID，主键，供其他表做外键';

ALTER TABLE pubud.sys_role_resource MODIFY `ROLE_ID` BIGINT NOT NULL COMMENT '角色ID';

ALTER TABLE pubud.sys_role_resource MODIFY `RESOURCE_ID` BIGINT NOT NULL COMMENT '资源ID';

ALTER TABLE pubud.sys_role_resource MODIFY `OBJECT_VERSION_NUMBER` BIGINT DEFAULT 1 NOT NULL COMMENT '行版本号，用来处理锁';

ALTER TABLE pubud.sys_role_resource MODIFY `CREATION_DATE` datetime DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间';

ALTER TABLE pubud.sys_role_resource MODIFY `CREATED_BY` BIGINT DEFAULT 1 NOT NULL COMMENT '创建人';

ALTER TABLE pubud.sys_role_resource MODIFY `LAST_UPDATED_BY` BIGINT DEFAULT 1 NOT NULL COMMENT '上次更新人';

ALTER TABLE pubud.sys_role_resource MODIFY `LAST_UPDATE_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '上次更新时间';