spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pubud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
      database: 4
      host: 127.0.0.1
      port: 6379
      pool:
        max-active: 8
        max-wait: 8
        min-idle: 0
        max-idle: 8
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*Mapper.xml
mapper:
  mappers: org.cgic.commons.mapper.BaseMapper
